### ISSUE TITLE
BSOD when trying to hook (KERNEL_SECURITY_CHECK_FAILURE)

### ISSUE THREAD

**Issue by BadPlayer555** [vmcall/dxgkrnl_hook#5]
This is my source: https://github.com/BadPlayer555/DxgkrnlHook
I have tried to start the driver with kdmapper in both my Vmware vm and my host PC and same result. This only happens when I am trying to replace the pointer.

Window version 1903
This is my output of my Driver from my VM:
[+] Hello from kernel mode! 
[+] Found w module_base FFFFF33E17000000.
[+] NtGdiDdDDISubmitCommand: FFFFF33E17260B92
[+] submit_command_address: FFFFF33E17260B92
[+] instruction: FFFFF33E17267044
[+] delta: 00000000FFFA8DB5
[+] DxgkSubmitCommand: FFFFF33E1720FE00
[+] original_entry: FFFFF33E1720FE00
[+] original_submit_command: 00007102DBA82318
[+] hooked original_entry: FFFFF33E1720FE00
[+] Hooked DxgkSubmitCommand!

I have resolved the NtGdiDdDDISubmitCommand symbol in windbg and it is the same as the Driver.
fffff33e`17260b92 win32kbase!NtGdiDdDDISubmitCommand = <no type information>

And I have checked the instruction Address in Windbg:
![Screenshot (410)](https://user-images.githubusercontent.com/24754464/78906415-e2bc1b00-7ab1-11ea-8db2-3cf9e655386e.png)

I have also checked the DxgkSubmitCommand Address in Windbg:
![Screenshot (411)](https://user-images.githubusercontent.com/24754464/78907103-d3899d00-7ab2-11ea-9b1f-43116938cd38.png)

This is the dump of the VM.
[Dump.zip](https://github.com/vmcall/dxgkrnl_hook/files/4456790/Dump.zip)

I just can't figure out what I was wrong about.

**Comment by ajkhoury** [comment]
just bypass patchguard bro
